name: 'agentic_data_modeling'
version: '1.0.0'
config-version: 2

profile: 'agentic_data_modeling'

model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  agentic_data_modeling:
    staging:
      +materialized: view

    intermediate:
      +materialized: view

    marts:
      +materialized: table